import {AboutContainer, Headshot, HeadshotWrapper, Bio} from './AboutStyles.jsx'
import {SectionContainer, Subheading, SectionLink, SupportLink} from '../../globalStyles.jsx'
import headshot from '../../assets/Images/Headshot.png';

function About(){
    return(

        <SectionContainer>
        <SectionLink id = "about">0</SectionLink>
        <Subheading>About</Subheading>

        <AboutContainer>
            <HeadshotWrapper>
                <Headshot src= {headshot} alt="" />
            </HeadshotWrapper>
            <Bio>
                Hi, I’m Jonathan!  I’m a Computer Science student at Cornell University’s College of Engineering. I enjoy
                using programming to create purposeful applications and solve difficult problems.
                <br />
                 <br />
                I am currently working with the 
                {' '}<SupportLink href = "https://www.andrewhein.org/" target = "_blank">
                    Hein Lab
                </SupportLink>{' '}
                to develop a Python GUI that helps researchers correct and analyze fish trajectory
                data generated by Computer Vision models.
                <br />
                <br />
                When I’m not coding, you can find me reading, playing piano, or tending to my vegetable garden. 
                Thanks for stopping by!
            </Bio>
        </AboutContainer>

        </SectionContainer>
    )
}

export default About